ZombieParty/ZombieParty/Controllers/ZombieTypeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZombieParty_Models;
using ZombieParty_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;

namespace ZombieParty.Controllers
{
  public class ZombieTypeController : Controller
  {
        private readonly ZombiePartyDbContext _db;

        public ZombieTypeController(ZombiePartyDbContext zombiePartyDbContext, IWebHostEnvironment webHostEnvironment)
    {
      _db = zombiePartyDbContext;
    }


    public async Task<IActionResult> Index()
    {
     
      IEnumerable<ZombieType> objList = await _db.ZombieType.ToListAsync();
      return View(objList);
    }

    //GET CREATE
    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ZombieType zombieType)
    {
      if (ModelState.IsValid)
      {
       await _db.ZombieType.AddAsync(zombieType);
       await _db.SaveChangesAsync(); // pour que les changements soient appliqués dans BD

        return RedirectToAction("Index");
      }
      return View(zombieType);
    }


    //GET - EDIT
    public async Task<IActionResult> Edit(int? id)
    {
      //retrouver le bon enr selon le id et le passer à la view, si il existe
      if (id == null || id == 0)
      {
        return NotFound();
      }
      // _db.ZombieType retourne tous les enregistrements
      // Find() cherche avec la clé primaire
      var obj = await _db.ZombieType.FindAsync(id.GetValueOrDefault());
      if (obj == null)
      {
        return NotFound();
      }
      return View(obj);
    }


    //POST EDIT
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> Edit(ZombieType zombieType)
    {
      {
        if (ModelState.IsValid)
        {
          _db.Update(zombieType);
          await _db.SaveChangesAsync();

          return RedirectToAction("Index");
        }
        return View(zombieType);
      }
    }

    //GET DELETE
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || id == 0)
        {
          return NotFound();
        }

        var obj = await _db.ZombieType.FindAsync(id.GetValueOrDefault());
        if (obj == null)
        {
          return NotFound();
        }

        return View(obj);
      }

    //POST DELETE
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> DeletePost(int? id)
    {
        var obj = await _db.ZombieType.FindAsync(id.GetValueOrDefault());
        if (obj == null)
        {
          return NotFound();
        }

            _db.ZombieType.Remove(obj);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
      }

  }
}

ZombieParty/ZombieParty/Views/ZombieType/Create.cshtml
@model ZombieParty_Models.ZombieType
<form method="post" asp-action="Create">
  <div class="border p-3">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
      <h2 class="text-info pl-3">Zombie Type</h2>
      <hr />
    </div>

    <div class="row">
      <div class="col-8">
        <div class="form-group row">
          <div class="col-2">
            <label asp-for="TypeName"></label>
          </div>
          <div class="col-8">
            <input asp-for="TypeName" class="form-control" />
            <span asp-validation-for="TypeName" class="text-danger"></span>
          </div>
        </div>

        <div class="form-group row py-2">
          <div class="col-8 offset-2 row">
            <div class="col">
              <input type="submit" class="btn btn-info w-100" value="Create" />
            </div>
            <div class="col">
              <a asp-action="Index" class="btn btn-success w-100">Back to list</a>
            </div>
          </div>
        </div>

      </div>
      <div class="col-4">

      </div>
    </div>
  </div>
</form>
@section Scripts{

  @{
    <partial name="_ValidationScriptsPartial" />
  }

}

ZombieParty/ZombieParty/Views/ZombieType/Index.cshtml
<div class="container p-3">
  <div class="row pt-4">
    <div class="col-10">
      <h2 class="text-primary">Zombie Type</h2>
    </div>
    <div class="col-2 text-right">
      <a asp-controller="ZombieType" asp-action="Create" class="btn btn-success">
        Create New Type
      </a>
    </div>
  </div>

  <br /><br />
  <table class="table table-bordered table-striped" style="width:100%">
    <thead class="bg-dark text-white">
      <tr>
        <th>
          Type Name
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in this.ViewBag.MaListe)
      {
        <tr>
          <td width="80%">@item.TypeName</td>
          <td class="text-center">
            <div class="w-75 btn-group" role="group">
              <a class="btn btn-warning mx-2">
                Edit
              </a>
              <a class="btn btn-danger mx-2">
                Delete
              </a>
            </div>
          </td>
        </tr>
      }
    </tbody>
  </table>
</div>