ZombieParty/ZombieParty/Controllers/ZombieController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using ZombieParty_DataAccess.Data;
using ZombieParty_Models;
using ZombieParty_Models.ViewModels;
using ZombieParty_Utility;

namespace ZombieParty.Controllers
{
  public class ZombieController : Controller
  {
        private readonly ZombiePartyDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

    public ZombieController(ZombiePartyDbContext zombiePartyDbContext, IWebHostEnvironment webHostEnvironment)
    {
            _db = zombiePartyDbContext;
            _webHostEnvironment = webHostEnvironment;
    }
    
    public async Task<IActionResult> Index()
    {
      ZombieCardVM zombieCardVM = new ZombieCardVM()
      {
        
        Zombies = await _db.Zombie.Include(z => z.ZombieType).ToListAsync(),
        ZombieTypes = await _db.ZombieType.ToListAsync()
      };
      return View(zombieCardVM);

    }

    //GET UPSERT
    public async Task<IActionResult> Upsert(int? id)
    {
            ZombieVM zombieVM = new ZombieVM()
            {
                Zombie = new Zombie(),
                ZombieTypeSelectList = (IEnumerable<SelectListItem>)await _db.ZombieType.ToListAsync()
      };
      if (id == null)
      {
        //CREATE
        return View(zombieVM);
      }
      else
      {
       //EDIT
        zombieVM.Zombie = await _db.Zombie.FindAsync(id.GetValueOrDefault());
        if (id == null || id == 0)
        {
          return NotFound();
        }
        return View(zombieVM);
      }
    }


    //POST - UPSERT
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Upsert(ZombieVM zombieVM)
    {
      if (ModelState.IsValid) //validation côté serveur
      {
        var files = HttpContext.Request.Form.Files; //nouvelle image récupérée
        string WebRootPath = _webHostEnvironment.WebRootPath; //Chemin des images zombies

        //Selon si Insert ou Update
        if (zombieVM.Zombie.Id == 0)
        {
          //Insert  
          string upload = WebRootPath + AppConstants.ImageZombiePath; //ServeurProjet + la constante du chemin relatif
          string fileName = Guid.NewGuid().ToString(); //Récupérer le nom du fichier
          string extension = Path.GetExtension(files[0].FileName);//extraire l'extension (pour Nom fichier complet)

          // Créer le nouveau fichier dans le dossier upload
          using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
          {
            files[0].CopyTo(fileStream);
          }

          //Update l'image dans le form
          // choix de gérer le path préalable ici ou ailleurs
          zombieVM.Zombie.Image = fileName + extension;

          await _db.Zombie.AddAsync(zombieVM.Zombie); //Ajouter dans la BD
          TempData[AppConstants.Success] = "Zombie created Successully";
        }
        else
        {

          //Update
          var objFromDb = await _db.Zombie.FirstOrDefaultAsync(u => u.Id == zombieVM.Zombie.Id);

          if (files.Count > 0)
          {
            string upload = WebRootPath + AppConstants.ImageZombiePath; //ServeurProjet + la constante du chemin relatif
            string fileName = Guid.NewGuid().ToString(); //Récupérer le nom du fichier
            string extension = Path.GetExtension(files[0].FileName);//extraire l'extension (pour Nom fichier complet)

            //Supprimer l'ancien fichier physiquement pour le remplacer (edit)
            if(objFromDb.Image != null)
            { 
            var oldFile = Path.Combine(upload, objFromDb.Image);

            if (System.IO.File.Exists(oldFile))
            {
              System.IO.File.Delete(oldFile);
            }
            }
            // Créer le nouveau fichier dans le dossier upload
            using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
            {
              files[0].CopyTo(fileStream);
            }

            zombieVM.Zombie.Image = fileName + extension;

          }
          else //si image pas modifiée
          {
            zombieVM.Zombie.Image = objFromDb.Image;
          }

          //Update
          _db.Update(zombieVM.Zombie); // Mettre à jour dans DB
          TempData[AppConstants.Success] = "Zombie modified Successully";
        }

        await _db.SaveChangesAsync(); // pour que les changements soient appliqués dans BD
        return RedirectToAction("Index");
      }
            zombieVM.ZombieTypeSelectList = (IEnumerable<SelectListItem>)await _db.ZombieType.ToListAsync();
      TempData[AppConstants.Error] = "Error while working on zombie";
      return View(zombieVM); //retourne l'objet pour avoir les données et messages d'erreur
    }

  
    //GET DELETE
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null || id == 0)
      {
        return NotFound();
      }

      var obj = await _db.Zombie.FindAsync(id.GetValueOrDefault());
      if (obj == null)
      {
        return NotFound();
      }

      return View(obj);
    }

    //POST DELETE
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> DeletePost(int? id)
    {
      var obj = await _db.Zombie.FindAsync(id.GetValueOrDefault());
            if (obj == null)
      {
        return NotFound();
      }

      _db.Zombie.Remove(obj);
      await _db.SaveChangesAsync();

      return RedirectToAction("Index");
    }
  }
}

ZombieParty/ZombieParty/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index"  class="btn btn-success form-control">Back to List</a>
    </div>
</div>

ZombieParty/ZombieParty/Views/Shared/_DeleteAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button asp-action="DeletePost" class="btn btn-danger form-control" asp-route-id="@Model">Delete</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

ZombieParty/ZombieParty/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-warning form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index"  class="btn btn-success form-control">Back to List</a>
    </div>
</div>

ZombieParty/ZombieParty/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZombieParty</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ZombieParty</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Zombies
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" asp-controller="Zombie" asp-action="Index">Manage Zombies</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2022 - ZombieParty - Valérie Turgeon <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ZombieParty/ZombieParty/Views/Shared/_Notifications.cshtml
@using ZombieParty_Utility


@if (TempData[AppConstants.Success] != null)
{
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

  <script type="text/javascript">
  toastr.success('@TempData[AppConstants.Success]');
  </script>
}

@if (TempData[AppConstants.Error] != null)
{
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

  <script type="text/javascript">
  toastr.error('@TempData[AppConstants.Error]');
  </script>

}

ZombieParty/ZombieParty/Views/Shared/_ZombieCard.cshtml
@model ZombieParty_Models.Zombie
@using ZombieParty_Utility

<div class="col-lg-4 col-md-6 pb-4">
  <div class="card border-primary rounded shadow-sm" style="background: url('/images/imagesLayout/fond.png');">
    <div class="card-body px-3 pt-3 pb-1 row">
      <p class="card-title text-center text-warning h5"><b>@Model.Name</b></p>
    </div>
    @if (@Model.Image == null)
    {
      <img class="card-img-top img-fluid d-block mx-auto mb-3" src="/images/Zombies/GenericZombie.png" alt="Zombie photo" style="width:85%">
    }
    else
    {
      <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@AppConstants.ImageZombiePath@Model.Image" alt="Zombie photo" style="width:85%">
    }
  <div class="card-body p-1 px-3 row">
    <div class="col-6" style="padding-left:25px;">
      <span class="badge p-2 border w-100 btn-dark">@Model.ZombieType.TypeName</span>
    </div>
    <div class="col-6" style="padding-left:3px;padding-right:25px;">
      <span class="badge p-2 border w-100 btn-primary">FORCE</span>
    </div>
    <div style="padding-left:25px;">
      <p class="text-white">Points: <span><b class="">@Model.Point</b></span></p>
    </div>
    
  </div>
    <a asp-route-Id="@Model.Id" asp-action="Upsert" class="p-2 border w-100 btn btn-warning px-3">
      Update/Show Detail Card
    </a>
    <hr />
  </div>
</div>